'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MyOLRibbon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot; loadImage=&quot;GetImage&quot; onLoad=&quot;OnRibbonLoad&quot;&gt;
        '''  &lt;ribbon startFromScratch=&quot;false&quot;&gt;
        '''    &lt;tabs&gt;
        '''      &lt;tab id=&quot;tabTLS&quot; label=&quot;TLS&quot;&gt;
        '''        &lt;group id=&quot;grpDept&quot; autoScale=&quot;true&quot; centerVertically=&quot;true&quot; label=&quot;Departments&quot; getImage=&quot;GetImage&quot;&gt;
        '''          &lt;menu id=&quot;mnuProjMgr&quot; size=&quot;large&quot; itemSize=&quot;large&quot; label=&quot;Project Managers&quot; getImage=&quot;GetImage&quot;&gt;
        '''            &lt;menuSeparator id=&quot;sepPM&quot; title=&quot;Proje [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Amanda() As String
            Get
                Return ResourceManager.GetString("Amanda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property briefcase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("briefcase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gear_user_group() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear_user_group", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gears_user_group() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gears_user_group", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iAccountingGrp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iAccountingGrp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iAddFolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iAddFolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iAmandaTime2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iAmandaTime2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iArchiveFolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iArchiveFolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iARKST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iARKST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iARKTLS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iARKTLS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iASmedley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iASmedley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iAsstPrjMgrGrp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iAsstPrjMgrGrp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iCCrenshaw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iCCrenshaw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iCWillis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iCWillis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iDWillis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iDWillis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iEmail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iEmail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iExecGrp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iExecGrp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iFleetAdmin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iFleetAdmin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iFleetMgr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iFleetMgr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iGForbes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iGForbes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iHaleeTime2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iHaleeTime2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iJButler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iJButler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iJFissel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iJFissel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iLButler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iLButler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iLeaAnnTime2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iLeaAnnTime2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iLForbes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iLForbes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iLocateCompass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iLocateCompass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iLocateTicket() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iLocateTicket", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iMCreps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iMCreps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iMechanic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iMechanic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iMechanicGrp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iMechanicGrp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iMechanicHelper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iMechanicHelper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iMove2Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iMove2Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iNewFolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iNewFolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iOKCGrp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iOKCGrp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iOKCST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iOKCST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iOKCTLS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iOKCTLS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iOpenFolder2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iOpenFolder2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iOTavilson() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iOTavilson", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iProjMgr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iProjMgr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iProjMgrGrp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iProjMgrGrp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iPurchMgr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iPurchMgr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iReceptionGrp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iReceptionGrp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iReceptionist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iReceptionist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iRefreshControls() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iRefreshControls", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iRFindley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iRFindley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iSafety2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iSafety2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iSafety3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iSafety3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iSafetyGrp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iSafetyGrp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iShop2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iShop2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iShop3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iShop3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iShopGrp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iShopGrp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iST1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iST1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iST2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iST2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iSTSmallJobs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iSTSmallJobs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iSTTransparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iSTTransparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iSTWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iSTWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iTButler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTButler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iTCarothers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTCarothers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iTech() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTech", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iTechGrp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTechGrp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iTLSSmallJobs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTLSSmallJobs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iTLSTransparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTLSTransparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iTLSWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTLSWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iTULST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTULST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iTULTLS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTULTLS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iTWillis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTWillis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iUpdateFolders() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iUpdateFolders", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iUser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iUser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iUserBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iUserBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iUserGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iUserGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iUserPurple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iUserPurple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iUserRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iUserRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iWFloyd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iWFloyd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iWKennedy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iWKennedy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
